project_id = "jfrryhkiupkddexcbvqa"

[functions.google-calendar-auth]
verify_jwt = true

[functions.google-calendar-callback]
verify_jwt = false

[functions.ai-routine-recommendations]
verify_jwt = true

[functions.generate-routine-recommendations]
verify_jwt = false

[functions.send-push-notifications]
verify_jwt = false

[functions.calculate-travel-time]
verify_jwt = true

[functions.place-autocomplete]
verify_jwt = true

[functions.chat]
verify_jwt = true

[functions.get-weather]
verify_jwt = true

[functions.weather-recommendation]
verify_jwt = true
